version: '3'
services:
  redis-server:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  node-app:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - '9000:3000'
